source 'http://rubygems.org'

gem 'sinatra'
gem 'toystore'
gem 'adapter-mongo'
gem 'bson_ext', '1.2.4'
gem 'yajl-ruby'
gem 'typhoeus'
gem 'curb'
gem 'carrierwave'
gem 'mini_magick'
gem 'capfire'
gem 'capistrano'
gem 'api_cache'
gem 'navvy'
gem 'mongoid'
gem 'rake'
gem 'hoptoad_notifier'

group :test do
  gem 'rspec', '2.1'
  gem 'rack-test'
  gem 'steak', '~> 1.0'
  gem 'fuubar'
  gem 'fakeweb'
end
